### ISSUE TITLE
Feat: whatsapp Logo Link for Footer

### ISSUE THREAD

**Issue by TenzDelek** [subhadeeproy3902/BloxAI#100]
### Describe the feature

adding whatapp direct link in footer

### Add ScreenShots

<img width="1255" alt="image" src="https://github.com/subhadeeproy3902/BloxAI/assets/122612557/fe9d49ca-08e9-4b24-8ff9-4dcbdd93d3f9">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AMANKANOJIYA** [comment]
LGTM
