### ISSUE TITLE
Feat:Add Scroll Back To Top Button

### ISSUE THREAD

**Issue by Wafmulla** [subhadeeproy3902/BloxAI#101]
### Describe the feature

Add Scroll Back To Top Button
 Can you assign this issue to me under GSSOC 24 label

### Add ScreenShots

![image](https://github.com/subhadeeproy3902/BloxAI/assets/114606506/1ca0587f-5db7-44d1-b4bf-2e070db9b579)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Wafmulla** [comment]
Yes sure

**Comment by Wafmulla** [comment]
Can you please assign this issue to me under gssoc label so that i will start working on it.

**Comment by chitraa-cj** [comment]
Assign me this issue please
