### ISSUE TITLE
Feat: to maximise or minimize the documentation section of the screen

### ISSUE THREAD

**Issue by AdhithiManjunath** [subhadeeproy3902/BloxAI#106]
### Describe the feature

i would like to add on this feature where u can increase or decrease the screen division  which separates the draw area and document area . i want to work on this issue , please assign me so thaat i can contribute 

### Add ScreenShots

![WhatsApp Image 2024-05-19 at 12 46 40_77236f17](https://github.com/subhadeeproy3902/BloxAI/assets/130202961/82250923-3070-4f42-949b-22468f55d188)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
its already done !
"with Editor | Fullscreen"
And fullscreen editor isnt reqd for now
@AdhithiManjunath
