### ISSUE TITLE
BUG: The AboutUs link in footer not redirecting 

### ISSUE THREAD

**Issue by Aniket-2504** [subhadeeproy3902/BloxAI#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello @subhadeeproy3902 ,

## The Issue is -

 The "About Us" link in the footer of the website. The link does not redirect properly when clicked, which can lead to a poor user experience.

Could you please assign this task to me? I am confident that I can resolve the issue promptly.

## Screenshot - 

I am attaching the screenshot for more understanding -

https://github.com/subhadeeproy3902/BloxAI/assets/145179532/02c0c8e4-be02-4641-a181-a0647f98144f

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Because there is currently no about us page !

**Comment by Aniket-2504** [comment]
Can I build the page If you want

**Comment by subhadeeproy3902** [comment]
> Can I build the page If you want

sure

**Comment by Aniket-2504** [comment]
Thank you so much @subhadeeproy3902 , I Iwill give my best
