### ISSUE TITLE
Enhancement: Integration of Next.js

### ISSUE THREAD

**Issue by codercake** [subhadeeproy3902/BloxAI#112]
**Description**:
To enhance the performance, SEO capabilities, and developer experience of our existing application, we should integrate Next.js, a powerful React framework.

**Steps to Implement**:
1. Evaluate the current structure and dependencies of the application to ensure compatibility with Next.js.
2. Create a plan for migrating existing components and pages to Next.js.
3. Set up Next.js configuration files and adjust project settings as needed.
4. Refactor existing React components to follow Next.js conventions and best practices.

**Benefits of Next.js Integration**:
- Improved performance: Next.js provides server-side rendering out of the box, resulting in faster page load times and improved SEO.
- Simplified routing: Next.js simplifies client-side routing with its built-in routing system, eliminating the need for additional routing libraries.
- Enhanced developer experience: Next.js offers features like hot module replacement and automatic code splitting, making development more efficient and enjoyable.

**Assignment**:
Please assign this issue to me **https://github.com/codercake** under the "**gssoc**" and "**level 3**" label.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@codercake What do u think ??? our site is in HTML, CSS ? :)

**Comment by codercake** [comment]
> @codercake What do u think ??? our site is in HTML, CSS ? :)

just saw the tech stack, was about to add another issue.
