### ISSUE TITLE
BUG: Workspace diagram / flowchart data is not save 

### ISSUE THREAD

**Issue by CoderSwarup** [subhadeeproy3902/BloxAI#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when the use is create some diagram in the workspace and try to saved data is they give an message data save but when the user re access their file the data is not present their  only text data is saved but 

please assign me this issue i want to work on it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
check the site ... if u save the work then only it will be saved @CoderSwarup

**Comment by CoderSwarup** [comment]
@subhadeeproy3902  check this [video](https://fileport.io/ceptAU4gXVKD) data is not save

**Comment by subhadeeproy3902** [comment]
I didnt know this, alryt u can check on this 
although over here its saving and coming nicely .... still if user experience is getting hampered then try to fix this ....
thanks for sharing this too ! @CoderSwarup
