### ISSUE TITLE
Feat: Auto Commenting feature for PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [subhadeeproy3902/BloxAI#116]
### Describe the feature

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks

### Add ScreenShots

![PR merged](https://github.com/subhadeeproy3902/BloxAI/assets/115717746/9c47f087-d21d-459e-bd69-1fdc86d08fe8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@subhadeeproy3902 please assign me this issue under gssoc'24

**Comment by subhadeeproy3902** [comment]
Go ahead @Asymtode712
