### ISSUE TITLE
Feat: Add Getting Started Page

### ISSUE THREAD

**Issue by Asymtode712** [subhadeeproy3902/BloxAI#129]
### Describe the feature

The "Getting Started" page for Blox AI serves as an introductory guide designed to help new users quickly familiarize themselves with the platform. Blox AI is a powerful tool for crafting flowcharts and diagrams effortlessly. It enables users to seamlessly create visuals and rich documentation, collaborate with their teams, and enjoy secure sharing.

### Add ScreenShots

![getting-started](https://github.com/subhadeeproy3902/BloxAI/assets/115717746/d1f97db9-7a0b-4fd1-9f41-2d070831bb6e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@subhadeeproy3902 Can i work on this issue

**Comment by Asymtode712** [comment]
we can add information about Introduction to Blox AI, Creating Your First Diagram, Collaborative Features, Secure Sharing etc

**Comment by subhadeeproy3902** [comment]
usure go ahead @Asymtode712

**Comment by mukilan2815** [comment]
@subhadeeproy3902 Assign me this task i can work on this
