### ISSUE TITLE
Navigation Bar Issue

### ISSUE THREAD

**Issue by SanjanaBankar** [subhadeeproy3902/BloxAI#13]
Hello, 

**Is your feature request related to a problem? Please describe**
After reviewing the website, it seems the navigation bar is not clickable and it is not working as expected. 

**Describe the solution you'd like**
I would like to make sure that the navigation bar works smoothly while navigating to the respective sections of the website.

I'm eager to take on this task and look forward to the opportunity to contribute to this project.

Please assign me this issue under GSSOC'24

**Comment by notSumit25** [comment]
Please add the gssoc and level label and Assign this task to me under gssoc'24, I have 1+ year of experience in React and Next.JS
