### ISSUE TITLE
Feat: Adding cancel button to create team modal.

### ISSUE THREAD

**Issue by PranotiPD** [subhadeeproy3902/BloxAI#130]
### Describe the feature

There is no cancel button available for creating a team modal. It would be a good user experience if we add one.

### Add ScreenShots

![Screenshot (766)](https://github.com/subhadeeproy3902/BloxAI/assets/97724414/f92a0a11-98da-46ce-b503-cdfef9daefb9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@PranotiPD but in the very first ... the user has to create a team ! ...

**Comment by PranotiPD** [comment]
in the very beginning, we will show it but when click on the Create Team button on the sidebar then we will give that option. @subhadeeproy3902

**Comment by PranotiPD** [comment]
yeah even idea of "My Org" sounds good. let me know which one to implement @subhadeeproy3902

**Comment by subhadeeproy3902** [comment]
Can be like if "Cancel" button is there !
Then a first team named "My Org" will be common for all !
Rest if the user likes to make a team then he is free to do so with the "Cancel" button as well 

Like in MONGO DB @PranotiPD
