### ISSUE TITLE
Feat: Showing all team members list

### ISSUE THREAD

**Issue by PranotiPD** [subhadeeproy3902/BloxAI#131]
### Describe the feature

As we are facilitating the feature of inviting more members to the team. It would be a good feature to show a list of them all.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Yes alryt ! @PranotiPD

**Comment by subhadeeproy3902** [comment]
This is being done by @Sid-80
