### ISSUE TITLE
BUG: Autocommenting Failing in workflow

### ISSUE THREAD

**Issue by subhadeeproy3902** [subhadeeproy3902/BloxAI#136]
![WhatsApp Image 2024-05-25 at 02 10 07_cc10503d](https://github.com/subhadeeproy3902/BloxAI/assets/111780029/e4066fb2-d194-4c94-bbc4-865643ea13e5)

![WhatsApp Image 2024-05-25 at 02 40 26_b9d13c96](https://github.com/subhadeeproy3902/BloxAI/assets/111780029/27fb0688-b716-4375-837f-fc3f3b381d41)

All these runs are failing except the greeting.yaml !

**Comment by RoshanAnsy** [comment]
Hey can you provide the more descriptions so that I can understand properly about this issue ?

**Comment by subhadeeproy3902** [comment]
Its completed @RoshanAnsy
