### ISSUE TITLE
Feat: Adding email validation to accept emails of approved domains like .com, .in, etc in the contact form 

### ISSUE THREAD

**Issue by Amruta7203** [subhadeeproy3902/BloxAI#138]
### Describe the feature

Current Functionality:

The existing contact form allows users to submit their email addresses, but it doesn't perform any validation. This can lead to receiving invalid email addresses, hindering communication and potentially impacting data quality.

Proposed Improvement:

I propose implementing email validation in the contact form, with a specific focus on verifying if the email address belongs to a registered domain. This will ensure:

Valid Email Format: 
Basic validation will check for the correct structure of an email address (e.g., containing "@" and "." symbols).
Registered Domain:
This feature would go beyond basic validation by attempting to verify if the domain name exists and is properly registered.

### Add ScreenShots

The contact form shown below does not display error when entered invalid email id:

![image](https://github.com/subhadeeproy3902/BloxAI/assets/116087736/0564f4cb-bdee-48ed-b6d8-eff7c25e2836)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Amruta7203** [comment]
@subhadeeproy3902 Request you to assign this to me under GSSOC'24

**Comment by subhadeeproy3902** [comment]
@Amruta7203  Sure go ahead... and do read the Contributing.md file

**Comment by Amruta7203** [comment]
@subhadeeproy3902 I am getting this error while running the website:
![image](https://github.com/subhadeeproy3902/BloxAI/assets/116087736/41b87b20-5614-48bc-8cbc-cbbdd0dbaa20)

Pls help me resolve this..

**Comment by subhadeeproy3902** [comment]
copy paste the env.example in env.local
run `npm i`
then npm run dev

**Comment by AdarshGT33** [comment]
Can I get this issue assigned?
