### ISSUE TITLE
Feat: Contact Form - Implement Success Message after submission

### ISSUE THREAD

**Issue by Amruta7203** [subhadeeproy3902/BloxAI#139]
### Describe the feature

Upon successful submission of the contact form, there's no feedback mechanism to inform users if their message has been received. This can leave them unsure whether their contact attempt was successful.

I propose implementing a success message that displays when a user submits the contact form with a valid email address (as proposed in #138 ). This message will provide confirmation and improve the overall user experience.

### Add ScreenShots

![image](https://github.com/subhadeeproy3902/BloxAI/assets/116087736/f0136dd7-c8ca-4d89-a2d8-dc0e66ad63cd)

the form does not display any msg after clicking on submit button.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
ok make sure that submissions reach to my email as well @Amruta7203

**Comment by Amruta7203** [comment]
Ok @subhadeeproy3902

**Comment by chitraa-cj** [comment]
Please assign this to me
