### ISSUE TITLE
Unauthorized Access To Dashboard

### ISSUE THREAD

**Issue by sarthakmishra459** [subhadeeproy3902/BloxAI#14]
# Issues Report for GSSOC'24 Contribution

### Description:
Currently, any user can access the dashboard page without being authenticated or logged in. This poses a security risk and violates the intended access control policy of the application. I would like to fix this issue.

### Potential Fix:
To address this issue and enforce authentication before accessing the dashboard, we can implement middleware in Next.js. Middleware functions can intercept incoming requests and perform checks, such as verifying if the user is authenticated, before allowing access to certain routes.

#### Steps to Implement Middleware for Authentication:

1. **Create Middleware Function:** Create a middleware function to check if the user is authenticated before allowing access to the dashboard route. This middleware can be a separate file or a function within the Next.js API routes.

    ```javascript
    // middleware/auth.js

    export function withAuth(handler) {
        return (req, res) => {
            // Perform authentication check
            if (/* User is authenticated */) {
                return handler(req, res);
            } else {
                return res.status(401).json({ error: 'Unauthorized' });
            }
        };
    }
    ```

2. **Apply Middleware to Dashboard Route:** Apply the `withAuth` middleware to the dashboard route in the Next.js application. This ensures that the middleware runs before accessing the dashboard page.

    ```javascript
    // pages/dashboard.js

    import { withAuth } from '../middleware/auth';

    function DashboardPage() {
        return (
            <div>
                {/* Dashboard content */}
            </div>
        );
    }

    export default withAuth(DashboardPage);
    ```

3. **Testing:** Test the application to ensure that unauthorized users are redirected or denied access to the dashboard page. Verify that authenticated users can still access the dashboard without any issues.

### Screenshot of the Issue:

![Unauthorised Access](https://github.com/subhadeeproy3902/BloxAI/assets/124512392/e70b5322-de0f-47cf-85d2-0b3119a0745e)

By implementing middleware for authentication in Next.js, we can ensure that only authorized users are able to access sensitive pages like the dashboard, thereby enhancing the security of the application.

**Comment by sarthakmishra459** [comment]
Kindly assign this issue to me

**Comment by subhadeeproy3902** [comment]
Go ahead @sarthakmishra459 . Will look forward to your PR
