### ISSUE TITLE
DOC: Update contributing.md file by adding git commands 

### ISSUE THREAD

**Issue by Amruta7203** [subhadeeproy3902/BloxAI#140]
### What's wrong with the existing documentation

The existing documentation does not contain git commands. It just mentions about the steps to follow while contributing.

### Add ScreenShots

![image](https://github.com/subhadeeproy3902/BloxAI/assets/116087736/dd3ac9bb-d6dd-40ef-a1ab-2ee3132fdf3f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@Amruta7203  go ahead
