### ISSUE TITLE
Feat: Home Page Sidebar Update

### ISSUE THREAD

**Issue by dfordp** [subhadeeproy3902/BloxAI#141]
### Describe the feature

- The GitHub Icon should navigate to the GitHub repo of the project , currently it navigates no where
- Settings tab should allow users to update their profile details such as profile pic , password , teams 
- Continuing with the second plan would be to integrate payment services such as stripe or razorpay into our application to ensure that a payment is followed allowing users to create unlimited files (as mentioned at the bottom of the sidebar) and allow us to develop premium features such as integration of gemini tools (mentioned in other issue) more optimally
- Lastly I feel that the we don't require the getting started and archive section as they don't serve any other purpose due to their not being a onboarding section & method to view our files 

### Add ScreenShots

![geg](https://github.com/subhadeeproy3902/BloxAI/assets/92905896/bb64178d-0889-4f0a-9495-5784ae57ebd3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@dfordp Upgrading to Pro... Wht features can be there ??
Archive will be there ... and also Docs has to be made for the project !
Rest the above mentioned things are already existing ... check for them and tag me up there

**Comment by dfordp** [comment]
Features to be included in a pro plan : 
- Using Gemini/Any LLM model to write/ create a template in the editor in the workspace that allows better documentation and elaboration  of the structures drawn on the Canvas
- Unlimited Files
Will add more features in the further requests

**Comment by subhadeeproy3902** [comment]
@dfordp  sure... unlimited files can be done... no need of gemini one though... cuz we wanna give it for free... 
do one thing.. make max 5 files and in successful stripe payment it gets to infinity

**Comment by subhadeeproy3902** [comment]
Will u be able to do this.. and i would really like if u can integrate gemini model to create diagrams as well.. its a pinned issue and i of a high priority... @dfordp

**Comment by dfordp** [comment]
Not to create diagrams in the canvas but creating or rewriting content in the editor for now eg proper documentation for  system design or logical structure drawn in the canvas 
![geg](https://github.com/subhadeeproy3902/BloxAI/assets/92905896/d298a89d-e714-4cb2-90a1-c48b50d2f26d)

**Comment by subhadeeproy3902** [comment]
ohh great go ahead... do a video record too.. when u make the PR.. so that i can understand... All the best @dfordp

**Comment by dfordp** [comment]
![geg](https://github.com/subhadeeproy3902/BloxAI/assets/92905896/888c2ffe-ec0c-4433-9074-67dd2fccef74)
you going to have to include a boolean field by the name of hasPremium with default has false this is the current status of the data being viewed or accessed by the developer

**Comment by dfordp** [comment]
Can you add a isPremium boolean field to the the user table set to false , this will allow us to maintain consistency

**Comment by dfordp** [comment]
@subhadeeproy3902 can you add this at the earliest

**Comment by subhadeeproy3902** [comment]
u can do the ispremium one... i am removing u from. the user table @dfordp

**Comment by dfordp** [comment]
There is a recurring issue where I have logged in through multiple email ids even after adding the field and it is not being updated 
probably because convex only accepts the fields which was already there before. Most probably it would have to be done from admin side

**Comment by dfordp** [comment]
Can you unassign me from this issue and allocate it someone else?

I am having trouble trying to make it work.

**Comment by subhadeeproy3902** [comment]
you have to make the api !!! ...
run `npx convex dev`
