### ISSUE TITLE
Feat: Add Privacy Policy page to enhance the website

### ISSUE THREAD

**Issue by AbhishiktaRay03** [subhadeeproy3902/BloxAI#145]
### Describe the feature

Your privacy policy commit enhances user trust by clearly outlining data protection measures, ensuring transparency and compliance with regulations. This commitment fosters user confidence, encouraging engagement and repeat visits to the website.

### Add ScreenShots

![Screenshot 2024-05-28 125323](https://github.com/subhadeeproy3902/BloxAI/assets/127621443/cf0bcbd2-6c12-4f20-89ad-e8ce894f2224)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Sure @AbhishiktaRay03 . Go ahead
