### ISSUE TITLE
Testimonials page

### ISSUE THREAD

**Issue by kairveeehh** [subhadeeproy3902/BloxAI#15]
there is no testimonial page as of now , I would like to contribute and add it for this website 
## please asign this issue to me under gssoc'24

**Comment by subhadeeproy3902** [comment]
I would ask u to make a form and send here. Also gather some testimonials of some users if u can get some it would be really helpful. Include all of those in a nice looking animated page altogether with whatever u want to like Framer motion and make sure to use SHADCN UI @kairveeehh

**Comment by kairveeehh** [comment]
> I would ask u to make a form and send here. Also gather some testimonials of some users if u can get some it would be really helpful. Include all of those in a nice looking animated page altogether with whatever u want to like Framer motion and make sure to use SHADCN UI @kairveeehh

You mean a form related to testimonials?

**Comment by subhadeeproy3902** [comment]
> > I would ask u to make a form and send here. Also gather some testimonials of some users if u can get some it would be really helpful. Include all of those in a nice looking animated page altogether with whatever u want to like Framer motion and make sure to use SHADCN UI @kairveeehh
> 
> You mean a form related to testimonials?

No i am asking u to  gather testimonials from a form ... Rest uk how to make a testimonials page !..
Give cool animations and u can use Aceternity UI as well

**Comment by kairveeehh** [comment]
ok suree

**Comment by amjido-01** [comment]
can i work on this also?
