### ISSUE TITLE
Feat: Add a delete button so that we can delete the team as well.

### ISSUE THREAD

**Issue by RoshanAnsy** [subhadeeproy3902/BloxAI#150]
### Describe the feature

Once the team has been created, the delete button will be visible, allowing me to delete the team if needed.

### Add ScreenShots

![Screenshot 2024-05-29 173403](https://github.com/subhadeeproy3902/BloxAI/assets/91673102/af6eea00-d499-4b32-ba9a-0ef3ab142ae3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Sure go ahead @RoshanAnsy

**Comment by chitraa-cj** [comment]
Assign this to me please
