### ISSUE TITLE
BUG: Making an Profile page responsive 

### ISSUE THREAD

**Issue by CoderSwarup** [subhadeeproy3902/BloxAI#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when the user see thier profile page in mobile screen that Is not responsive 

![Screenshot_2024-05-30-00-48-59-84_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/subhadeeproy3902/BloxAI/assets/128630311/f57bf47e-44ff-4891-8bea-475f108c44ea)

And one more issue is when the user side bar is open and user try to open profile page is getting an overflow 

![Screenshot_2024-05-30-00-48-29-22_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/subhadeeproy3902/BloxAI/assets/128630311/8d21b6a6-43ea-4f5d-90f9-f23e784cee71)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Yes sure ! @CoderSwarup
