### ISSUE TITLE
Some part of the screen is being cut on being viewed on devices

### ISSUE THREAD

**Issue by sarthakmishra459** [subhadeeproy3902/BloxAI#16]
# Issues Report for GSSOC'24 Contribution

### Description:
When viewing the application on various devices, such as mobile phones or tablets, some parts of the screen are being cut off, leading to a poor user experience.

### Potential Fix:
To address this issue and improve the user experience, we need to make the application responsive. Responsive design ensures that web pages render well on a variety of devices and window or screen sizes.

### Screenshot of the Issue:
![Upgrade Plan Issue](https://github.com/subhadeeproy3902/BloxAI/assets/124512392/5d7053a5-ecad-4c56-9454-1d33ccf97064)

By implementing these responsive design techniques, we can ensure that the application adapts to different devices and screen sizes, providing a better user experience for all users.

**Comment by subhadeeproy3902** [comment]
Great @sarthakmishra459 . Try to make the project responsive and make sure to use SHADCN and Sheet specially for hamburger menus and all. All the best
