### ISSUE TITLE
BUG: About button in nav bar is not working properly.

### ISSUE THREAD

**Issue by himanshi-0908** [subhadeeproy3902/BloxAI#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we clicking on the About button on nav bar it doesn't work.
![Screenshot (9)](https://github.com/subhadeeproy3902/BloxAI/assets/147384570/0477f63a-573c-40d9-9989-7ee71b03c66a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@himanshi-0908 There is no about us page and this issue has already been raised
