### ISSUE TITLE
Footer not present

### ISSUE THREAD

**Issue by kshavp** [subhadeeproy3902/BloxAI#17]
The landing page for the project can have a nice footer.

@subhadeeproy3902 this issue can be assigned to me.

**Comment by ask2901** [comment]
Hello @subhadeeproy3902 I would like to work on this feature. Kindly assign me this task.

**Comment by aashkaaaaaa** [comment]
The landing page for the project can have a nice footer.

@subhadeeproy3902 please assign this issue to me.

**Comment by Xeven777** [comment]
Assigned y'all! Happy contributing 😊 @kshavp @ask2901 @aashkaaaaaa

**Comment by ParnaRoyChowdhury777** [comment]
@subhadeeproy3902 I want to contribute in GSSOC' 24.

**Comment by subhadeeproy3902** [comment]
> @subhadeeproy3902 I want to contribute under GSSOC' 24.

Sure go ahead ! @ParnaRoyChowdhury777

**Comment by TheAshutoshGupta** [comment]
@subhadeeproy3902 and @Xeven777  I would like to add footer section, responsive and compatible with the dark and light mode, please assign this issue to me.
