### ISSUE TITLE
[Other] Found some typing mistakes

### ISSUE THREAD

**Issue by NIKHIL0VERMA** [subhadeeproy3902/BloxAI#177]
hey @subhadeeproy3902 ,
I found several typos and would like to fix them under GSSOC'24.
Kindly, assign me and add the correct labels.

**Comment by subhadeeproy3902** [comment]
what typos u found @NIKHIL0VERMA

**Comment by subhadeeproy3902** [comment]
show me some examples

**Comment by NIKHIL0VERMA** [comment]
In contributing.md at line 161 `necesarry` is written.  and 6 more changes.

**Comment by subhadeeproy3902** [comment]
@NIKHIL0VERMA add urself in Contributors.ts .... while contributing u should read these !

**Comment by NIKHIL0VERMA** [comment]
Hey @subhadeeproy3902 ,
Actually, I just got confused whether I should add myself or not because of this line that says `This file serves as a repository of the individuals who are **actively involved** in improving our platform.`
Thankx of clearing, will add my details soon.

**Comment by subhadeeproy3902** [comment]
> Hey @subhadeeproy3902 , Actually, I just got confused whether I should add myself or not because of this line that says `This file serves as a repository of the individuals who are **actively involved** in improving our platform.` Thankx of clearing, will add my details soon.

no any contribution u make... u give ur contribution details.... its an open source and contributors are to given their contribution rewards thats why

**Comment by subhadeeproy3902** [comment]
@NIKHIL0VERMA send a pr registering ur contribution details as mentioned asap

**Comment by NIKHIL0VERMA** [comment]
@subhadeeproy3902 kindly check PR linked just now.
Thanks for understanding.
