### ISSUE TITLE
BUG: Fixing Sidebar on mobile & tablet viewpoints (enhance User experiences)

### ISSUE THREAD

**Issue by Vaibhavsg17** [subhadeeproy3902/BloxAI#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the sidebar is not proper on mobile  & tablet view which can create bad user experience

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vaibhavsg17** [comment]
@subhadeeproy3902 assign me this i want to create a better user experience  on mobile & tablet view

**Comment by subhadeeproy3902** [comment]
Send an ss of the issue @Vaibhavsg17

**Comment by Vaibhavsg17** [comment]
![image](https://github.com/subhadeeproy3902/BloxAI/assets/66477893/47a65691-0c97-4c68-b432-a066e4fd6666)
![image](https://github.com/subhadeeproy3902/BloxAI/assets/66477893/1df7d3c5-b638-470c-9638-5626351d0e42)
@subhadeeproy3902

**Comment by subhadeeproy3902** [comment]
ok @Vaibhavsg17 u can fix this ...

**Comment by subhadeeproy3902** [comment]
And do read Contributing.md
