### ISSUE TITLE
[Bug] Missing Review Page

### ISSUE THREAD

**Issue by Manav173** [subhadeeproy3902/BloxAI#18]
Problem:
Currently, the website lacks a dedicated space for users to provide feedback or report any issues they encounter while using the platform.

Solution:
Implement a review page which will serve as a centralized hub for collecting user feedback, enabling us to enhance the user experience and resolve any issues efficiently.

I would be really thankful if you assign me this issue as a part of GSSoC'24 @subhadeeproy3902 .

**Comment by subhadeeproy3902** [comment]
Go ahead @Manav173 . also contact details you will get from my github
