### ISSUE TITLE
Feat: create Better Light/Dark mode effect distinguishing each component

### ISSUE THREAD

**Issue by Vaibhavsg17** [subhadeeproy3902/BloxAI#180]
### Describe the feature

- I want to create a better  light screen for light mode, and the same for dark mode which helps easily to distinguish various components on the screen in light mode
- Enhance User Experience.

### Add ScreenShots

![image](https://github.com/subhadeeproy3902/BloxAI/assets/66477893/6ba99278-51d8-48f2-8f6c-ac013eaa2840)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vaibhavsg17** [comment]
@subhadeeproy3902 please assign me this issue

**Comment by subhadeeproy3902** [comment]
@Vaibhavsg17 send ss in the PR if u make it
