### ISSUE TITLE
DOC: Adding back to top to the README.

### ISSUE THREAD

**Issue by rithika212k3** [subhadeeproy3902/BloxAI#188]
### What's wrong with the existing documentation

**Can you assign me this issue?**
-Adding back to the top link at the bottom right of the readme document, this change enhances the usability and navigation of the document.
-It is a modification to the content or structure of the README to improve the user experience when reading the documentation.

### Add ScreenShots

![backtotop](https://github.com/subhadeeproy3902/BloxAI/assets/158501895/b4e1a8df-fb8d-4f1c-9e8b-d190870e51cc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rithika212k3** [comment]
Hi @subhadeeproy3902 ,
Can you assign me this issue?

**Comment by rithika212k3** [comment]
Thank you for assigning me this issue @subhadeeproy3902 .😊

**Comment by rithika212k3** [comment]
@subhadeeproy3902 , I have opened the PR can you please look into it?

**Comment by subhadeeproy3902** [comment]
Hey @rithika212k3 if i click on that `Back to top` then its not going to the top of the page, the second time .... So i reverted ur PR
