### ISSUE TITLE
[Bug] Contact Page missing

### ISSUE THREAD

**Issue by roysammy123** [subhadeeproy3902/BloxAI#19]
## Issue: Contact Page Not Opening/Missing When Clicking on Navbar Contact Button

**Issue:**
When users click on the "Contact" button in the navigation bar, the contact page is not loading as expected. This creates a frustrating experience for users who are trying to reach out or access the contact information.

**Expected Behavior:**
Upon clicking on the "Contact" button in the navbar, users should be directed to the contact page where they can find relevant contact information or a contact form.

**Actual Behavior:**
Clicking on the "Contact" button does not lead users to the contact page. Instead, it simply does not respond.

**Comment by Xeven777** [comment]
@roysammy123 u are assigned. Good to go 😇

**Comment by Xeven777** [comment]
and please use shadcn components :)

**Comment by roysammy123** [comment]
Okay, will get started on this! Thanks for assigning :)

**Comment by komal-agarwal5** [comment]
@subhadeeproy3902 Please assign me this task under GSSoC'24

**Comment by roysammy123** [comment]
Hi @subhadeeproy3902 , just reminding you that I have already raised a PR against this issue which is waiting to be merged
