### ISSUE TITLE
Feat: Adding a feature section

### ISSUE THREAD

**Issue by subhadeeproy3902** [subhadeeproy3902/BloxAI#196]
The website needs a feature section. The features are listed in the `README.md`. Frame those up and form a **responsive**  section like this ->

![image](https://github.com/subhadeeproy3902/BloxAI/assets/111780029/11bafbb6-aee1-42ad-9ed6-13e8763e12fe)

Give cool svg animations. Show a video of what you have built in the PR and do read the `Contributing.md` before contributing

**Comment by Vaibhavsg17** [comment]
@subhadeeproy3902 Assign me

**Comment by Vaibhavsg17** [comment]
i will do this on first priority

**Comment by subhadeeproy3902** [comment]
@Vaibhavsg17 go ahead... i assigned it to u... dont copy... but u can make svg animations as per our website feature says

**Comment by subhadeeproy3902** [comment]
@Vaibhavsg17 ok ... the features section should be like the above with the things i mentioned

**Comment by subhadeeproy3902** [comment]
@Vaibhavsg17 By when will u be able to complete this ?? ... with a nice looking bento grid style UI of the feature section

**Comment by Vaibhavsg17** [comment]
@subhadeeproy3902 I will raise pr till tomorrow evening

**Comment by subhadeeproy3902** [comment]
@Vaibhavsg17 if u already made it then show me in the grp....
