### ISSUE TITLE
Feat: Implementing new features to Editor Js in the workspace

### ISSUE THREAD

**Issue by subhadeeproy3902** [subhadeeproy3902/BloxAI#197]
Currently only some features are there those are include. Here are the added items right now
![image](https://github.com/subhadeeproy3902/BloxAI/assets/111780029/1c59e47a-53c0-4159-b01a-769e2e5667d4)

want the below things like in [notion.so](https://www.notion.so/) :

https://github.com/subhadeeproy3902/BloxAI/assets/111780029/69abd012-2216-41cc-8d7d-9ad8c600b79c

Applying the AI with gemini will be also required ... if u can do it then thats a great enhancement in the website

**Comment by Sid-80** [comment]
@subhadeeproy3902 Assign me this issue
