### ISSUE TITLE
Feat: Making the profile and dashboard respponsive

### ISSUE THREAD

**Issue by chitraa-cj** [subhadeeproy3902/BloxAI#206]
### Describe the feature

The dashboard and profile in smaller screens are not resposive

### Add ScreenShots

Not needed

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chitraa-cj** [comment]
Please assign this to me

**Comment by subhadeeproy3902** [comment]
@chitraa-cj done
