### ISSUE TITLE
[Feature]: Develop Responsive About Page 

### ISSUE THREAD

**Issue by Vaibhavsg17** [subhadeeproy3902/BloxAI#21]
I'm reaching out to express my interest in contributing to our project by adding an About Page.

An About Page is a crucial component of any project as it provides valuable information about the project's purpose, mission, and the team behind it. By adding an About Page, we can enhance the project's credibility and provide users with a clear understanding of what we aim to achieve.

**Comment by Vaibhavsg17** [comment]
@subhadeeproy3902 assign this to me

**Comment by subhadeeproy3902** [comment]
> @subhadeeproy3902 assign this to me

Sure... assigned it to ya

**Comment by Vaibhavsg17** [comment]
I will create a new About page. including information about Blox AI and its Features

**Comment by Vaibhavsg17** [comment]
@subhadeeproy3902 please increase the level tag to level 3
