### ISSUE TITLE
[Feature]: Adding Full Screen mode for excalidraw

### ISSUE THREAD

**Issue by 0plaze0** [subhadeeproy3902/BloxAI#22]
The drawing Board from excalidraw only covers half of the screen which make it very uncomfortable for some user to draw on it.

Expected Behavior:
Add a toggle button the allows to swap between full-screen and half-screen mode.

Actual Behavior:
Clicking on the "full-screen" button will allow to switching to full-screen and normal mode.

I would be really thankful if you kindly assign me to work on this issue as part of GSSoC'24.

**Comment by subhadeeproy3902** [comment]
Go ahead and use shadcn and lucide icons please to main the compatibility @0plaze0
