### ISSUE TITLE
BUG:In mobile view , the navbar is not there an hamberger menu is not implemented

### ISSUE THREAD

**Issue by Adeesh-bode** [subhadeeproy3902/BloxAI#23]
The issue details a bug affecting the mobile version of a website or application where the navigation bar is missing, and a hamburger menu (typically used for mobile-friendly navigation) has not been implemented. This problem severely affects mobile users' ability to navigate the site effectively, likely leading to a poor user experience. The task would involve designing and implementing a responsive hamburger menu to ensure that mobile users can access all parts of the website or app efficiently.

**Comment by Xeven777** [comment]
@Adeesh-bode ✅ assigned. Be sure to use shadcn components and lucide icons, especially the sheet component to make a responsive hamburger menu for mobiles😊 happy contributing
