### ISSUE TITLE
Feat: Working review form 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [subhadeeproy3902/BloxAI#233]
### Describe the feature

I will create a working review form so that the feedback can be go on the direct email

### Add ScreenShots

![Screenshot 2024-06-08 131950](https://github.com/subhadeeproy3902/BloxAI/assets/118350936/917a49de-4ff6-48cf-bf41-e640da14fc30)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ayushmaanagarwal1211** [comment]
@subhadeeproy3902 i will use emailjs for email functionality if you want some other let me know ?

**Comment by chitraa-cj** [comment]
Assign this to me
