### ISSUE TITLE
Feat: Dockerizing application

### ISSUE THREAD

**Issue by PranotiPD** [subhadeeproy3902/BloxAI#234]
### Describe the feature

I would like to add a docker file to the project so that we can run the application using a docker image.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@PranotiPD I didnt understand this ! ... why is Docker needed here ?

**Comment by PranotiPD** [comment]
to locally run the project by using a docker image. @subhadeeproy3902

**Comment by subhadeeproy3902** [comment]
No like why shall i run with a docker image ??? ... It runs smoothly with `npm run dev`. What is the advantage ??

**Comment by PranotiPD** [comment]
yeah, it does. Ok, fine we can avoid doing it. I'll close the issue.
