### ISSUE TITLE
Feat: All files section on side nav bar

### ISSUE THREAD

**Issue by PranotiPD** [subhadeeproy3902/BloxAI#237]
### Describe the feature

Shall we add all the file names below that all files section in sidenavbar ?
or is it reserved for something else. 

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@PranotiPD something else ... Files are to be displayed on in the dashboard area...
