### ISSUE TITLE
Feat: Making share link in workspace private

### ISSUE THREAD

**Issue by PranotiPD** [subhadeeproy3902/BloxAI#239]
### Describe the feature

Whenever the share link is shared and pasted in the browser then it will open only if the user has logged in otherwise it will prompt the user to log in in order to see the link.

### Add ScreenShots

--

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@PranotiPD that part is being done by @Sid-80 along with invited member.
