### ISSUE TITLE
Feat:Newsletter section for engaging with users and collecting their emails

### ISSUE THREAD

**Issue by Adeesh-bode** [subhadeeproy3902/BloxAI#24]
The issue involves creating a newsletter section on a website or application to engage with users and collect their email addresses. This feature aims to facilitate communication with users, keep them informed about updates or promotions, and potentially increase user retention and interaction. The implementation would typically include designing the user interface for the newsletter signup, integrating it with the backend systems, and ensuring compliance with data protection regulations.

**Comment by amjido-01** [comment]
please @Adeesh-bode assign me to this issue under gssoc and please add the labels of GSSOC'24 and the label of appropriate level (like level 1, 2 or 3) on this issue.

**Comment by subhadeeproy3902** [comment]
Go ahead @Adeesh-bode

**Comment by amjido-01** [comment]
ok

**Comment by Adeesh-bode** [comment]
hey subhadeep , just a little discussion . Your project doesn't have proper backend as I can see in contact page, just data is collected but not stored. So for now I will create frontend for newsletter and make backend endpoints so that whenever backend database is used one can stored newsletter subscribers email. Will it be ok , to have newsletter frontend as you did for contact form in contact page

**Comment by Adeesh-bode** [comment]
I would be happy to raise backend - mongodb as database by raising another issue , after frontend of newsletter is done. Let me know your opinion on it!!

**Comment by Adeesh-bode** [comment]
????

**Comment by subhadeeproy3902** [comment]
@Adeesh-bode first of all we do have a backend ... (proper one)... i dont want to implement newsletter section. In contact section, someone has already used formspree... but i am not implementing that for now ... first a bit of ui and main pinned issues are to be solved then these. Thank you
