### ISSUE TITLE
[BUG]: Contact form is not completely responsive 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [subhadeeproy3902/BloxAI#246]
### Describe the feature

Hii in small screen size the input field is overflowing from the form 

### Add ScreenShots

![Screenshot 2024-06-09 154912](https://github.com/subhadeeproy3902/BloxAI/assets/118350936/d46cc9c7-0ab0-4d2e-9214-0ae01856bb86)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
I checked it in my phone. Its totally alright @Ayushmaanagarwal1211
