### ISSUE TITLE
Adding animation by framer motion

### ISSUE THREAD

**Issue by Adeesh-bode** [subhadeeproy3902/BloxAI#25]
The issue involves creating a newsletter section on a website or application to engage with users and collect their email addresses. This feature aims to facilitate communication with users, keep them informed about updates or promotions, and potentially increase user retention and interaction. The implementation would typically include designing the user interface for the newsletter signup, integrating it with the backend systems, and ensuring compliance with data protection regulations.

**Comment by Xeven777** [comment]
Sorry, but we're not interested to add a newsletter section anytime soon 🙁. We are closing this isuue.

(you can always go ahead and create a new issue to add another feature or improvement tho)😇😉
