### ISSUE TITLE
Feat: BackToTop Button is not present in the Contributors and Review Us section

### ISSUE THREAD

**Issue by Damini2004** [subhadeeproy3902/BloxAI#250]
### Describe the feature

Yes, the request for a "Back to Top" button is related to the problem of user experience on long web pages. When users scroll down through lengthy content, it becomes cumbersome to manually scroll back up to the top. This can be particularly annoying on mobile devices where continuous scrolling can be tedious.

### Add ScreenShots

![image](https://github.com/subhadeeproy3902/BloxAI/assets/119414762/3d5241d6-c772-46f5-affc-3ec687f37322)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Go ahead @Damini2004. Do check the Contributing.md

**Comment by chitraa-cj** [comment]
assign this to mw
