### ISSUE TITLE
Ui animation in navbar

### ISSUE THREAD

**Issue by Adeesh-bode** [subhadeeproy3902/BloxAI#26]
The issue involves enhancing the user interface by adding animations to the navigation bar. This feature aims to improve the visual appeal and user experience of the website or application by making the navigation more dynamic and engaging. The task would typically include designing subtle animations that activate when users interact with the navbar elements, such as hovering over links or clicking on menu items, without compromising the usability or performance of the site.

**Comment by Anil0Sharma** [comment]
hey i want to resolve this issue so could you assign it to me

**Comment by Ahmad102938** [comment]
hello admin I want to work on this issue under gssoc24 please assign it
