### ISSUE TITLE
Feat: Add invitation of members to the team via sending them emails

### ISSUE THREAD

**Issue by subhadeeproy3902** [subhadeeproy3902/BloxAI#268]
Currently members are invited to the team with sharing of the link or code copy pasting which is kinda old aged. But adding the members with sending them emails seem technical and professional. With the help of `resend` or `nodemailer` its going to be easy. Personally I recommend `resend`. Also multiple emails are to be send to the members by the admin.

**Comment by RamakrushnaBiswal** [comment]
hi @subhadeeproy3902 i can use resend to do that can i work upon it

**Comment by subhadeeproy3902** [comment]
sure @RamakrushnaBiswal ... contact me via whatsapp
