### ISSUE TITLE
Export Options such as PDF, PNG, and SVG Formats

### ISSUE THREAD

**Issue by sanskriti-lal** [subhadeeproy3902/BloxAI#278]
### Describe the feature

The Export Options feature in Blox AI empowers users with versatile export capabilities by offering PDF, PNG, and SVG formats for sharing and printing purposes. 

PDF Format: Ensures compatibility and high-quality output for sharing via email or embedding in documents.
PNG Format: Preserves graphics with a transparent background, ideal for social media sharing or web use.
SVG Format: Maintains sharp visuals for editing and scaling, suitable for designers and developers.

These export options cater to diverse user needs, ensuring seamless communication and flexibility in handling diagrams across various platforms and contexts.

### Add ScreenShots

<img width="1436" alt="Screenshot 2024-06-13 at 12 56 12 AM" src="https://github.com/subhadeeproy3902/BloxAI/assets/165655543/19255ca7-105f-48ad-84f3-57fe8a6add47">

I will add an export option there and then accordingly the user can select how they want to save their work.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@sanskriti-lal will be needing only in pdf and, need the pdf in a formated manner: -

- First the document
- Next at last the flowchart png.

will u be able to do so ??

**Comment by sanskriti-lal** [comment]
Yea sure, then I'll just add the pdf option there.

**Comment by subhadeeproy3902** [comment]
@sanskriti-lal  Pdf format :

```
Title of the document
Body of the document
Flowchart image extracted from the Excalidraw
```

**Comment by subhadeeproy3902** [comment]
Do read the contributing.md and u can send the final result to me via whatsapp

**Comment by sanskriti-lal** [comment]
Ok cool

**Comment by chitraa-cj** [comment]
please assign this to me
