### ISSUE TITLE
Feat: Add feedback type in Feedback form

### ISSUE THREAD

**Issue by AkhilaSunesh** [subhadeeproy3902/BloxAI#287]
### Describe the feature

Easy to segregate the issues

### Add ScreenShots

![WhatsApp Image 2024-06-14 at 15 12 33_7ea25036](https://github.com/subhadeeproy3902/BloxAI/assets/140897461/621ee147-6149-4cb7-9069-c8bc968ed06c)
![image](https://github.com/subhadeeproy3902/BloxAI/assets/140897461/d85f2fab-a44a-4c52-b3c2-5caa5d2c6164)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@AkhilaSunesh Not in contact page ... in the Reviews page

**Comment by AkhilaSunesh** [comment]
ok...I will do it in "reviews" page

**Comment by chitraa-cj** [comment]
Assign it to me
