### ISSUE TITLE
Feat: Creating Custom 404 not found page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [subhadeeproy3902/BloxAI#294]
### Describe the feature

the error page does not looks good

### Add ScreenShots

![image](https://github.com/subhadeeproy3902/BloxAI/assets/125277258/2a895465-f67f-4ae2-b979-1597fbd446a6)
now it something looks like we need to design it in a better manner

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@RamakrushnaBiswal Make a nice responsive one !!! and send the screenshot. and do read contributing.md

**Comment by Prakash-Raut** [comment]
Hi, I would love to work on this issue.

Solution: 
![image](https://github.com/subhadeeproy3902/BloxAI/assets/82020300/2dff9030-0f01-4c31-8b62-441ce81ab8ad)

Followup: This is a not-found-error page (404). Do you need a custom error page like global-error ?

Ref: https://nextjs.org/docs/app/building-your-application/routing/error-handling#handling-errors-in-root-layouts

![image](https://github.com/subhadeeproy3902/BloxAI/assets/82020300/70e82ddc-d98a-454b-ab50-d6a44c16a42c)

Thank you for your guidance on this. Please let me know if there are any further improvements or considerations.

**Comment by RamakrushnaBiswal** [comment]
hi @Prakash-Raut i working upon it you can find another issue
