### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [subhadeeproy3902/BloxAI#30]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by subhadeeproy3902** [comment]
Cool go ahead @suhanipaliwal

**Comment by suhanipaliwal** [comment]
Could you please add the labels of GSSOC'24 and the label of appropriate level (like level 1, 2 or 3) on this issue.

**Comment by subhadeeproy3902** [comment]
> Could you please add the labels of GSSOC'24 and the label of appropriate level (like level 1, 2 or 3) on this issue.

sure, i forgot tbh. Thanks for reminding me
