### ISSUE TITLE
BUG: Profile setting

### ISSUE THREAD

**Issue by PranotiPD** [subhadeeproy3902/BloxAI#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

* Showing right prompt when there is no profile image to delete
![Screenshot (769)](https://github.com/subhadeeproy3902/BloxAI/assets/97724414/efd7f5f1-bd9e-4a4c-9900-585dc2c9ae94)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@PranotiPD already being done
