### ISSUE TITLE
Feat: Adding profile picture

### ISSUE THREAD

**Issue by PranotiPD** [subhadeeproy3902/BloxAI#303]
### Describe the feature

Adding profile picture when clicked on change profile button or pencil icon 
Using cloudinary to store the profile images.

### Add ScreenShots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@PranotiPD Already someone is working on it
