### ISSUE TITLE
Feat: Auto Comment when an issue is raised

### ISSUE THREAD

**Issue by chaanakyaaM** [subhadeeproy3902/BloxAI#310]
### Describe the feature

I would like to add an auto commenting feature to the repo, so that when ever a contributor raises a issue an auto comment is sent to their issue, this feature is very helpful to maintain the communication with the contributor, and more than that this feature makes the repo look professional.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@chaanakyaaM  do read contributing.md... when u raise the PR

**Comment by chaanakyaaM** [comment]
Sure
