### ISSUE TITLE
BUG:Even if no team , it shows team is deleted.

### ISSUE THREAD

**Issue by mukilan2815** [subhadeeproy3902/BloxAI#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/subhadeeproy3902/BloxAI/assets/71129858/f8d000c7-3762-4df6-b6a7-2f43d1fd1bf8)

When no team is there it should show the user to create a team first message

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
send me a video....
cuz auto team gets created automatically @mukilan2815
