### ISSUE TITLE
BUG: Sign-Up Button for Unauthenticated Users is Non-functional on /dashboard 

### ISSUE THREAD

**Issue by awesohame** [subhadeeproy3902/BloxAI#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The sign-up button on the /dashboard page does not work when the user is not logged in. This issue prevents unauthenticated users from accessing the sign-up functionality directly from the dashboard. 

Steps to Reproduce:

Navigate to the /dashboard page without logging in. (can be done through "Start now" button on the home page.)
Click on the sign-up button.

![img](https://github.com/subhadeeproy3902/BloxAI/assets/82087247/7d966066-f957-41de-91b9-81a8a9f457e1)
![404](https://github.com/subhadeeproy3902/BloxAI/assets/82087247/23502ca5-992e-428d-9395-f1d9c8c90ad7)

Expected Behavior:
The user should be redirected to the sign-up page by Kinde.

Actual Behavior:
404 page appears.

Please assign this issue to me under VSoC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chitraa-cj** [comment]
assign it to me
