### ISSUE TITLE
Feat: Footer section CSS style improvement,

### ISSUE THREAD

**Issue by sakeel-103** [subhadeeproy3902/BloxAI#315]
### Describe the feature

@subhadeeproy3902 
Hello admin, this is a requesting message that in the footer section there is not hover effects on the quick links, follow us, contact and legal tags. So please assign me this task under gssoc'24.

If you assign me this task, then I'll work on this to improve or add blinking effects.

### Add ScreenShots

Video -

https://github.com/subhadeeproy3902/BloxAI/assets/136844498/83fedb90-bf88-45f1-bcbd-20363b0b35ea

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sakeel-103** [comment]
dear admin please provide the terminal command or all steps to run the project in the server.

**Comment by subhadeeproy3902** [comment]
@sakeel-103 already provided
make a  .env.local file and paste the  .env.example content
run npm i
run npx convex dev
run npm run dev

**Comment by sakeel-103** [comment]
@subhadeeproy3902 
I'm not able to find the index.js page. sorry to tell you that I'm not a next.js developer but I'm trying to understand the codes and to solve.
I need help, if you guide me to find this then it will be best for me.

**Comment by KavyaBS123** [comment]
Hey @subhadeeproy3902 I am GSSOC contributor can you please assign this issue to me I would like to work on it!
