### ISSUE TITLE
Feat: Able to add images while making diagrams or flowcharts

### ISSUE THREAD

**Issue by Chelseasingla1** [subhadeeproy3902/BloxAI#32]
### Describe the feature

I would like to add a feature where one would be able to add/upload images too , to make flow charts more interactive.

### Add ScreenShots

Like this:
![image](https://github.com/subhadeeproy3902/BloxAI/assets/129886894/89372537-e0d8-4803-b77c-b1457fe922e9)

in this flowchart images are also there.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Good point of view and will be really helpful.. @Chelseasingla1 . Go ahead, will look for your PR

**Comment by Chelseasingla1** [comment]
> Good point of view and will be really helpful.. @Chelseasingla1 . Go ahead, will look for your PR

@subhadeeproy3902 thankyou!!

**Comment by PranotiPD** [comment]
There is an inbuilt button given for it @subhadeeproy3902
