### ISSUE TITLE
improving styling of login and signup page

### ISSUE THREAD

**Issue by mahek0620** [subhadeeproy3902/BloxAI#320]
### What's wrong with the existing documentation

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by KavyaBS123** [comment]
Hey @subhadeeproy3902 I am VSoc Contributor can you please assign this issue to me I would like to work on it!

**Comment by subhadeeproy3902** [comment]
@mahek0620 @KavyaBS123 The login and signup page is a 3rd party serviced auth system. You cant modify that !
