### ISSUE TITLE
BUG:  Paragraph Overflowing from Features Card

### ISSUE THREAD

**Issue by Saksham2k3s** [subhadeeproy3902/BloxAI#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The paragraph text in the features card is overflowing from the card's boundary. This issue causes the text to extend beyond the card's edges, disrupting the layout and visual appearance of the feature section.

![text-overflow](https://github.com/subhadeeproy3902/BloxAI/assets/129402285/0669d8fc-860e-4757-8fa7-bae827324a46)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@Saksham2k3s do read COntributing.md while making a PR and list up your contributions
