### ISSUE TITLE
[Bug] : `Nav bar` mismatch color

### ISSUE THREAD

**Issue by sivaprasath2004** [subhadeeproy3902/BloxAI#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- In this application `mobile` site cannot proper approach by the `Nav bar` , because the nav can background can't proper.
- `Half` nav can be black and another half is transparent approach..
- please assign me ..
### Screen shot

![Screenshot from 2024-06-18 14-11-39](https://github.com/subhadeeproy3902/BloxAI/assets/121082414/2f0f29f1-9ede-4d86-bfdb-a32cf231f476)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@sivaprasath2004 do read COntributing.md while making a PR and list up your contributions
