### ISSUE TITLE
Feat: File Conversion

### ISSUE THREAD

**Issue by Cralsic123** [subhadeeproy3902/BloxAI#33]
### Describe the feature

An inbuilt feature to convert any file to pdf, ppt, jpeg or any other format so that it can be downloaded easily.

### Add ScreenShots

<img width="903" alt="Screenshot 2024-05-12 at 6 29 50 PM" src="https://github.com/subhadeeproy3902/BloxAI/assets/101086033/ba354cd8-eedb-4e1f-a5dd-5ae4ef362d78">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Cralsic123** [comment]
@subhadeeproy3902 Please assign me this issue, I want to work on it.

**Comment by subhadeeproy3902** [comment]
> @subhadeeproy3902 Please assign me this issue, I want to work on it.

What's the solution ?
You want that the Editor Js document will be downloaded as a pdf ?

**Comment by Cralsic123** [comment]
Yes, it will be downloaded not only as pdf but if the user wants it in the form of ppt, jpeg and etc.
Does it sound good?

**Comment by subhadeeproy3902** [comment]
Go ahead @Cralsic123. Also I would like u to contribute for issue #29 if its okay with u. Try enhancing more of this project. Thank you, will be looking for your PR

**Comment by Cralsic123** [comment]
Yeah sure I would like to contribute to issue #29 
Please assign me that too.

**Comment by subhadeeproy3902** [comment]
please comment there @Cralsic123

**Comment by Cralsic123** [comment]
Hi @subhadeeproy3902 I created a new branch on my former repo added the files there and then pushed it and pressed compare and pull request and after that its showing this
<img width="1280" alt="Screenshot 2024-05-12 at 11 14 28 PM" src="https://github.com/subhadeeproy3902/BloxAI/assets/101086033/ebe46314-276e-4f11-b23c-177d53cdf82e">

**Comment by subhadeeproy3902** [comment]
@Cralsic123 are u doing this issue resolve ?
