### ISSUE TITLE
Feat: No hovering effect on the review us section cards

### ISSUE THREAD

**Issue by sakeel-103** [subhadeeproy3902/BloxAI#333]
### Describe the feature

@subhadeeproy3902 
If you would like to have the hover effect on the cards in the "Review Us" section, please assign this task to me under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@sakeel-103 I wanted a new reviews section
