### ISSUE TITLE
Feat: Add Preloader

### ISSUE THREAD

**Issue by AsmitaMishra24** [subhadeeproy3902/BloxAI#336]
### Describe the feature

Design and Appearance:
1. A simple and visually appealing animation.
2. Should match the overall design language of the application.
3. Customizable options for color, size, and style to fit different themes.

Functionality:
1. Should display during the loading of heavy components or data fetching processes.
2. Must cover the main content area that is being loaded.
3. Option to show the preloader globally (entire screen) or locally (specific component).

Performance:
1. Lightweight and optimized to prevent additional load times.
2. Should not interfere with the loading process of the main content.

Implementation:
1. Should be implemented as a reusable component.
2. Easy to integrate with different parts of the application.
3. Must include appropriate documentation for usage and customization.

### Add ScreenShots
My Previous Work:-
https://github.com/subhadeeproy3902/BloxAI/assets/146121869/a6c41891-eabd-4042-8950-4919d17fad90

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@AsmitaMishra24 If u can create a unique loader according to the theme of and the logo 
(or do a logo svg creation animation) .... I would be increasing the level of the PR from 1 to 2
And do read `Contributing.md`

**Comment by subhadeeproy3902** [comment]
thats cool ... check out our logo ... u can try animating it :) ...

**Comment by AsmitaMishra24** [comment]
https://github.com/subhadeeproy3902/BloxAI/assets/146121869/79590b3a-6091-4f1c-b990-e65713869b66

@subhadeeproy3902, I have created an animation for the logo. Please take a look and let me know if any changes are needed.

**Comment by AsmitaMishra24** [comment]
> Recording.2024-06-28.223554.mp4 
> @subhadeeproy3902, I have created an animation for the logo. Please take a look and let me know if any changes are needed.

@subhadeeproy3902

**Comment by subhadeeproy3902** [comment]
@AsmitaMishra24 Its perfect .... just make the edged sharp ... rest its perfect
