### ISSUE TITLE
Feat: Adding Linked, Discord, Instagram accounts and twitter.

### ISSUE THREAD

**Issue by GAVINESHWAR** [subhadeeproy3902/BloxAI#348]
### Describe the feature

In this website there is no social media accounts like Linked, Discord, Instagram and twitter i would like add those features to the project.

@subhadeeproy3902, please assign me this issue so that I can contribute to the project.

Thank you

### Add ScreenShots

![image](https://github.com/subhadeeproy3902/BloxAI/assets/124431955/8998ca33-cb9e-49d0-ba97-a757b3920af0)
![image](https://github.com/subhadeeproy3902/BloxAI/assets/124431955/561b6081-ac3e-46bf-bcf8-6a34066c81ec)

here only whatsapp and github accounts only there

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@GAVINESHWAR there are no such social media handles. So not needed
