### ISSUE TITLE
Feat: Showing the number of contributions made by a contributor

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [subhadeeproy3902/BloxAI#369]
### Describe the feature

I will add the number of contributions made my each contributor in the contributors page

### Add ScreenShots

![Screenshot 2024-06-27 194333](https://github.com/subhadeeproy3902/BloxAI/assets/118350936/baa23c79-e606-46a2-8566-246cadfdc63a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
If only u can make it dynamic then i will be increasing the level. Else its gonna be not worthy

**Comment by Ayushmaanagarwal1211** [comment]
Yes yes I will make it dynamic by fetching official api to fetch all the details about the contributors and to show the real time data
