### ISSUE TITLE
Feat: Adding particles Animation

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [subhadeeproy3902/BloxAI#371]
### Describe the feature

I will add a particles animation on the header which makes it more  attractive . 
I am attaching the reference of the particles but if you want any other particles let me know 

### Add ScreenShots

![Screenshot 2024-06-27 195651](https://github.com/subhadeeproy3902/BloxAI/assets/118350936/22aa9bf3-a378-430b-9241-5e5f30d79eb4)

https://github.com/subhadeeproy3902/BloxAI/assets/118350936/cf2cae9b-add9-4d78-863a-13be8ff271b5

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Too much animation isnt liked by everyone
