### ISSUE TITLE
Add Icons To Navbar 

### ISSUE THREAD

**Issue by sailaja-adapa** [subhadeeproy3902/BloxAI#379]
### Describe the feature

Hello Project Admin
I would like to add icons to Navbar 

### Add ScreenShots

![IMG_20240629_231721](https://github.com/subhadeeproy3902/BloxAI/assets/161804629/bb602cb3-5e68-4bb8-85e6-6177296306bd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Not required @sailaja-adapa
