### ISSUE TITLE
Feat: Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [subhadeeproy3902/BloxAI#38]
### Describe the feature

I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me.

### Add ScreenShots

![image](https://github.com/subhadeeproy3902/BloxAI/assets/50082154/5e602b6a-1b42-4508-9d27-dcde3a498caa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Go ahead @sanmarg . Do as soon as possible

**Comment by sanmarg** [comment]
The task is completed.
