### ISSUE TITLE
Feat: Add Contact Functionality  ("Sales Contact Form" or "Enterprise Plan Inquiry Form.")

### ISSUE THREAD

**Issue by Vaibhavsg17** [subhadeeproy3902/BloxAI#39]
### Describe the feature

The proposed feature involves adding contact functionality to the application. Users will have the option to contact our sales team directly through the app. Upon selecting the contact option, users will be directed to a form where they can input their contact information and a brief message. Once the form is submitted, our sales team will receive the information and reach out to the user to discuss how an Enterprise Plan can boost collaboration and productivity across teams and workflows.

I would like to have a dedicated contact functionality integrated into the app, allowing users to easily connect with our sales team. The feature should include a form where users can input their name, email address, phone number, and a brief message outlining their inquiry or interest in upgrading to an Enterprise Plan. Upon submission of the form, the information should be forwarded to our sales team for follow-up.

### Add ScreenShots
Example : -
![image](https://github.com/subhadeeproy3902/BloxAI/assets/66477893/8f452997-714d-43cc-b2d9-e0e74f1b4a55)
![image](https://github.com/subhadeeproy3902/BloxAI/assets/66477893/74f3d446-7a94-462d-abd2-605616f9c17b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by komal-agarwal5** [comment]
@subhadeeproy3902 Please assign me this task under GSSoC'24.

**Comment by Vaibhavsg17** [comment]
@komal-agarwal5 hello, I have already started working on this issue, you can raise any new issues or look for any other unassign issues
