### ISSUE TITLE
Feat: Add User Profile

### ISSUE THREAD

**Issue by Vaibhavsg17** [subhadeeproy3902/BloxAI#40]
### Describe the feature

The User Profile feature entails the creation of individual profiles for each user within the application. Upon signing up or logging in, users will have access to their personalized profile where they can view and manage their account information, preferences, and activity. **Basic Information**: Users will be able to view and edit their basic information such as name, email address, and profile picture. **Account Settings**: This section allows users to manage their account settings, including password changes, email notification preferences, and privacy settings.

### Add ScreenShots

Example:-
![image](https://github.com/subhadeeproy3902/BloxAI/assets/66477893/14ef0d10-3b38-402e-aa1f-d9accefce697)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Sure go ahead @Vaibhavsg17

**Comment by Vaibhavsg17** [comment]
Thanks @subhadeeproy3902 , also check the #39

**Comment by Sid-80** [comment]
@subhadeeproy3902 Please assign me this issue!

**Comment by subhadeeproy3902** [comment]
> @subhadeeproy3902 Please assign me this issue!

done
