### ISSUE TITLE
Feat:Adding Live links to the linkedin accounts of the people displayed onto the page 

### ISSUE THREAD

**Issue by Debarunn1806** [subhadeeproy3902/BloxAI#41]
### Describe the feature

Live links can be added to the icons displaying the pictures of the team members to increase accessibility.

### Add ScreenShots

![Screenshot 2024-05-13 024256](https://github.com/subhadeeproy3902/BloxAI/assets/106834322/45b54264-8839-4d60-9a30-6410a67de7b3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
We would rather prefer a team section where the Contributors will be the Core and displayed nicely and the rest contributors will be shown like this ... including the linkedin links.
