### ISSUE TITLE
Feat: Next auth and mongodb

### ISSUE THREAD

**Issue by Sid-80** [subhadeeproy3902/BloxAI#413]
### Why this is needed ?

Here we are using kinde which is having following disadvantages :
1. Not scalable
2. No jwt token management
3. Hard to make other api secure

### What Next-Auth and mongodb brings ?

Next-auth brings following advantages:
1. OAuth implementation
2. JWT implementation which will help to secure APIs

Let me know your views!!

### Add ScreenShots

Not required!!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Xeven777** [comment]
ohh , u were talking about next-auth.  cool :)

**Comment by subhadeeproy3902** [comment]
@Sid-80 remove existing kinde and convex and add next auth and mongo
Change whole backend. All the best

**Comment by Sid-80** [comment]
@Xeven777 Yepp!! with jwt authentication

**Comment by Sid-80** [comment]
@subhadeeproy3902 I will go ahead!! Thank you!!
