### ISSUE TITLE
Feat: Sign In Page

### ISSUE THREAD

**Issue by Sid-80** [subhadeeproy3902/BloxAI#414]
### What are you developing?

While developing the nextauth and mongdb to test the login and sign in page will be required.
I am willing to develop the sign in page for it!!

This issue will target following advancements :
1. Develop given template : 
     https://ui.shadcn.com/blocks
     authentication-4
2. Form validation

Let me know if any changes required!!

### Add ScreenShots

![image](https://github.com/subhadeeproy3902/BloxAI/assets/101277141/b9735f9a-8be1-4e35-bbbb-b8e3f776c124)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sid-80** [comment]
@subhadeeproy3902 I will be doing everything in single one only

**Comment by Sid-80** [comment]
@subhadeeproy3902 Please provide the fields required while registering as user

**Comment by subhadeeproy3902** [comment]
@Sid-80 
First Name.
Last Name. 
Email. 
Password
Confirm Password. 

And google auth
