### ISSUE TITLE
Feat: improve hover effect of footer

### ISSUE THREAD

**Issue by heli0707** [subhadeeproy3902/BloxAI#418]
### Describe the feature

To improve the footer hover effect, make it visually appealing by adding smooth color changes and animations. This creates a more engaging and interactive experience when users move their mouse over the footer elements.

### Add ScreenShots

https://github.com/subhadeeproy3902/BloxAI/assets/95361125/de456fb5-ad03-4f1b-93b7-2a8b85d19312

something like this 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
As of now its not required @heli0707
