### ISSUE TITLE
BUG: Redux-persist

### ISSUE THREAD

**Issue by Sid-80** [subhadeeproy3902/BloxAI#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Uploading freecompress-Recording 2024-07-06 224819.mp4…

This will happen when the page will be reloaded.
To tackle this error, we have to integrate the redux-persist into redux for persistence of state.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Uploading freecompress-Recording 2024-07-06 224819.mp4…

Video ??
@Sid-80

**Comment by Sid-80** [comment]
Not able to upload that's why I have uploaded on WhatsApp group
