### ISSUE TITLE
Add Contributors

### ISSUE THREAD

**Issue by subhadeeproy3902** [subhadeeproy3902/BloxAI#44]
As the owner of the Blox AI repository, I'm initiating an important discussion regarding the documentation of contributor details. It's imperative for all collaborating individuals to ensure their information is accurately recorded in the `src/app/contributors/ContributorsData.ts` file. This ensures proper recognition and attribution for their valuable contributions.

Key Points:

1. **Submission Reminder**: I urge all collaborators who have not yet submitted their details to promptly do so by adding their information to ContributorsData.ts. This includes their name, email address, GitHub username, and a brief overview of their contributions.

2. **Strict Adherence**: Emphasize the importance of strict adherence to the guidelines outlined for submitting contributor details. Only individuals should add their own information, and any unauthorized modifications to existing entries will not be accepted.

All collaborators are requested to review the ContributorsData.ts file and ensure their details are accurately represented. This step is vital for maintaining transparency and recognizing the collective efforts that drive the success of the Blox AI project.

Your cooperation in this matter is greatly appreciated.

Fill up you details here: 

![image](https://github.com/subhadeeproy3902/BloxAI/assets/111780029/9c57da74-87b9-46f9-8e91-64041ac16e50)

**Comment by subhadeeproy3902** [comment]
@dakshsinghrathore @sarthakmishra459 @vanshikab52 
Do this asap. for listing your contributions in our site !. After that you can check it at here: https://blox-ai.vercel.app/contributors

**Comment by dakshsinghrathore** [comment]
@subhadeeproy3902 am out of station right now, will do it by tonight asap

**Comment by dakshsinghrathore** [comment]
@subhadeeproy3902 I have raised the PR, kindly review it and merge, whenever you are free.

**Comment by subhadeeproy3902** [comment]
@suhanipaliwal please do the needful... add your details in the `ContributorsData.ts` file

**Comment by subhadeeproy3902** [comment]
@sanmarg please do the needful... add your details in the `ContributorsData.ts` file

**Comment by subhadeeproy3902** [comment]
@PradnyaGaitonde please do the needful... add your details in the `ContributorsData.ts` file

**Comment by subhadeeproy3902** [comment]
@sanmarg @suhanipaliwal please add ur details in `ContributorsData.ts` and send a PR asap
