### ISSUE TITLE
Feat: Schemas

### ISSUE THREAD

**Issue by Sid-80** [subhadeeproy3902/BloxAI#440]
### Describe the feature

I am willing to implement the Schemas for File and Team.

### Add ScreenShots

Not required!!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sid-80** [comment]
@subhadeeproy3902 @Xeven777 
Please look into this issue

**Comment by subhadeeproy3902** [comment]
@Sid-80 
Files
Teams
Users
ig 3 are reqd

**Comment by Sid-80** [comment]
Users is implemented in previous PR
