### ISSUE TITLE
Feat: Sign in with google and jwt token 

### ISSUE THREAD

**Issue by Sid-80** [subhadeeproy3902/BloxAI#448]
### Describe the feature

As per the discussion on WhatsApp group, I am willing to implement the sign in with google with jwt token

### Add ScreenShots

Not required!!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MinavKaria** [comment]
@Sid-80 @subhadeeproy3902 Assign this to me

**Comment by Ojas-Arora** [comment]
@subhadeeproy3902 I have a good Experience of working on this issue. Kindly assign me this.
