### ISSUE TITLE
Feature 🧑‍💻✨: Add progress bar in scroll to top button

### ISSUE THREAD

**Issue by TheNikhilRaj** [subhadeeproy3902/BloxAI#465]
### Describe the feature

Describe the feature
Hey @subhadeeproy3902  ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no progress bar in the scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.

Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

Describe the solution you'd like
@subhadeeproy3902  ,Could you please assign me this issue under gssoc'24 ?

GSSOC'24

Describe alternatives you've considered
Add progress in scroll to top button!

### Add ScreenShots

![343755959-404f8025-9ca5-4dbc-b660-cac20005d1c3](https://github.com/user-attachments/assets/ad506aa1-2d4e-407c-9025-dfbb5ec28029)

@subhadeeproy3902 
/assign

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@TheNikhilRaj No need of intricate detailing
