### ISSUE TITLE
[Feature Request] : ✨ Add a Page Scroll Progress Bar at the Top of Your Startup Webpage

### ISSUE THREAD

**Issue by TheNikhilRaj** [subhadeeproy3902/BloxAI#466]
### Describe the feature

Explain feature request
Hey @subhadeeproy3902  ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no Page Scroll Progress Bar at the Top of Your Startup Webpage , which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

Explain your solution

### Add ScreenShots

![343870881-7f17e9d3-41c5-4fb0-a558-caf334552764](https://github.com/user-attachments/assets/3339af2d-878b-40aa-a9e1-cda07edb1910)

@subhadeeproy3902 
/assign

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@TheNikhilRaj It wont be looking nice over here. Though thanks for raising this issue
