### ISSUE TITLE
BUG: Whatsapp icon not proper

### ISSUE THREAD

**Issue by AMS003010** [subhadeeproy3902/BloxAI#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The whatsapp icon is not proper. It could be replaced with a proper icon. Also more social handles can be added if available.

![image](https://github.com/user-attachments/assets/3fcc3896-aed5-41e3-aaeb-eada87ef3b37)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@AMS003010 Change the linkedin too !
There should be only github and whatsapp icon

**Comment by AMS003010** [comment]
@subhadeeproy3902 
I have made a PR
Please do review
