### ISSUE TITLE
DOC: There should be a guide in the README.md file which shows how to get the required enviroment variables and set them in our app

### ISSUE THREAD

**Issue by dfordp** [subhadeeproy3902/BloxAI#48]
### What's wrong with the existing documentation

Need to add a clear cut guide for individuals to be able to add the services in their local environment , hence allowing for dynamic changes to the applications

### Add ScreenShots

![re2e](https://github.com/subhadeeproy3902/BloxAI/assets/92905896/b192ab61-2a08-4ad6-bf31-0915669422c1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@Xeven777 please look into it

**Comment by subhadeeproy3902** [comment]
> ### What's wrong with the existing documentation
> Need to add a clear cut guide for individuals to be able to add the services in their local environment , hence allowing for dynamic changes to the applications
> 
> ### Add ScreenShots
> ![re2e](https://private-user-images.githubusercontent.com/92905896/330082246-b192ab61-2a08-4ad6-bf31-0915669422c1.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDg2NTQsIm5iZiI6MTcxNTYwODM1NCwicGF0aCI6Ii85MjkwNTg5Ni8zMzAwODIyNDYtYjE5MmFiNjEtMmEwOC00YWQ2LWJmMzEtMDkxNTY2OTQyMmMxLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEzNTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNzE4YjdiNTA5Zjc5MjgwYTYxYTc5MGMxMDFiYjg0MTA3YzMwNjQzMDIzZDkzNjUxZGFhMjhlZjc1MWZjNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dn-TZCjMbrEuf1kNKcSqmKIU2Gn2yL0hq4lQd_4plho)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Thanks for your issue. Since we know how to get the env variables. Please lets us handle this ... By today you will get to know about this

**Comment by subhadeeproy3902** [comment]
> one more thing I would like to add kinde doesn't provide client secrets for single page applications how to resolve that issue

U will be able to get this right away by tonight @Xeven777 will help u in this when he updates the README.md

**Comment by subhadeeproy3902** [comment]
@dfordp .env variables are added ! you can check it
