### ISSUE TITLE
BUG: The canvas doesn't cover the entire screen properly

### ISSUE THREAD

**Issue by dfordp** [subhadeeproy3902/BloxAI#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The canvas doesn't cover the entire screen properly & leaves a lot of unnecessary negative/empty space when we zoom out 
the attachment I am adding is zoomed out at 90% only
![re2e](https://github.com/subhadeeproy3902/BloxAI/assets/92905896/1f02c297-e487-48ad-9df2-1d33443c1b8d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Fix it up @dfordp . It will be better if u provide a full screen button and exit full screen button as well for more professionalism. Also make sure to check the README will u are contributing

**Comment by subhadeeproy3902** [comment]
> there also one thing that the workspace header navigates to the landing page not the dashboard can I add it also?

Sure its a minor fix. and to join the Whatsapp grp for more discussions and help with problem resolving
