### ISSUE TITLE
Feat: Adding Facebook Authentication

### ISSUE THREAD

**Issue by Ojas-Arora** [subhadeeproy3902/BloxAI#498]
### Describe the feature

@subhadeeproy3902 I want to add Facebook Authentication using Firebase. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/25c8d520-8be3-4f65-848f-49779acfb41e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
This is in next auth so additionally firebase is not reqd... moreover facebook is not at all an auth likely platform
