### ISSUE TITLE
Feat: Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [subhadeeproy3902/BloxAI#54]
## Security Feature
In your application anyone can enter using **temporary or disposable email**.
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.
Assign me this work under GSSoC24, I will implement it.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Sure go ahead and please do check the contribution section of the README.md @pankaj-bind
