### ISSUE TITLE
BUG: Showing incorrect message while loading page

### ISSUE THREAD

**Issue by PranotiPD** [subhadeeproy3902/BloxAI#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In buffer time/ loading time of page it is showing below text. Instead of showing that text, we can add some loader there. 
![Screenshot (755)](https://github.com/subhadeeproy3902/BloxAI/assets/97724414/03f4e3ba-e4ab-41d1-88b6-297d1e173326)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Go ahead @PranotiPD . I am really impressed by your observations once again!
Use ShadCn and tailwind css for a loader !
Read the Contributors.md file before PR. Thank You. Will look forward to your PR

**Comment by subhadeeproy3902** [comment]
Also it will be better if u fix the UI of the page 
when not logged in 

![image](https://github.com/subhadeeproy3902/BloxAI/assets/111780029/de137e85-4e9e-4f53-9104-78ec7c80dabd)


This page looks simple, you can also upgrade it !
And i would ask for a favour, if u can send the video recording of what you built in the whatsapp group or in PR

**Comment by subhadeeproy3902** [comment]
@PranotiPD All the best !

**Comment by PranotiPD** [comment]
Sure! I will do the needful @subhadeeproy3902 .
