### ISSUE TITLE
BUG: Making whole file row clickable

### ISSUE THREAD

**Issue by PranotiPD** [subhadeeproy3902/BloxAI#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we click on the file name then only it redirects to the file. It would be great if we could click anywhere on the row and the file opens up.

### Record
![Screenshot (756)](https://github.com/subhadeeproy3902/BloxAI/assets/97724414/6858dc83-cded-4adb-b34b-940d53260896)

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Go ahead @PranotiPD . You have good observations
Read the Contributors.md file before sending PR
