### ISSUE TITLE
Feat: Delete prompt modal development

### ISSUE THREAD

**Issue by PranotiPD** [subhadeeproy3902/BloxAI#64]
### Describe the feature

Currently, when we click on the delete button on the file, the file gets deleted. but it would be great if we could show one modal where we ask for assurance of deleting the file to the user. 

### Add ScreenShots

![Screenshot (757)](https://github.com/subhadeeproy3902/BloxAI/assets/97724414/83e0ad21-6c66-4fb7-a143-02f370edcc2e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@PranotiPD Go ahead. and read the Contributors.md file and use Shadcn Components (Dont Change Globals.css file)
Thank u
