### ISSUE TITLE
BUG: Some fields getting hidden when switched to bright mode.

### ISSUE THREAD

**Issue by PranotiPD** [subhadeeproy3902/BloxAI#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we switch to bright mode some fields on the dashboard page are getting hidden.

![Screenshot (759)](https://github.com/subhadeeproy3902/BloxAI/assets/97724414/ab00c72d-e94e-462f-bad3-ab769c3c74ea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Need a good fix of it @PranotiPD . Go ahead . All the best 
Join the whatsapp group for further discussion. I will look forward to your PR

**Comment by subhadeeproy3902** [comment]
Also check the Contributors.md file
