### ISSUE TITLE
BUG: Missing Navbar in Contributors page

### ISSUE THREAD

**Issue by TenzDelek** [subhadeeproy3902/BloxAI#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the current contributor page is missing the navbar
<img width="1197" alt="image" src="https://github.com/subhadeeproy3902/BloxAI/assets/122612557/4bec87dc-7fc0-47a0-a537-7f66e73d6245">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Add it up @TenzDelek Also you can try to make the navbar responsive as well
