### ISSUE TITLE
BUG: Duplicate file name

### ISSUE THREAD

**Issue by ronisarkarexe** [subhadeeproy3902/BloxAI#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We can improve our file list by not allowing the creation of a new file with the same name as an existing file.

![dup](https://github.com/subhadeeproy3902/BloxAI/assets/76697055/14c38378-3d9e-4770-b6fe-f17da6e82022)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@ronisarkarexe Go ahead and read the Contributors.md file
