### ISSUE TITLE
Feat: View File Lists

### ISSUE THREAD

**Issue by ronisarkarexe** [subhadeeproy3902/BloxAI#74]
### Describe the feature

We are displaying a list of files. When we click on a file, it indicates that the file has already been viewed.
If we display the list of viewed items another route, it will enhance user experience.

### Add ScreenShots

![viewfiles](https://github.com/subhadeeproy3902/BloxAI/assets/76697055/00712193-7ac6-4e22-9386-4fd66da5da32)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@ronisarkarexe Ok go ahead

**Comment by subhadeeproy3902** [comment]
File list is shown in dashboard itself.... in the marked place you are free to raise new features and tell them
![image](https://github.com/subhadeeproy3902/BloxAI/assets/111780029/2f2eeda9-4808-4427-8263-45e30b5bd896)
