### ISSUE TITLE
Feat: Add file into Archive

### ISSUE THREAD

**Issue by ronisarkarexe** [subhadeeproy3902/BloxAI#75]
### Describe the feature

We can add a button to the file list and include the file in the Archive list.

### Add ScreenShots

![archive](https://github.com/subhadeeproy3902/BloxAI/assets/76697055/696fe9d0-1739-44d4-a323-8fabdcd14727)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@ronisarkarexe go ahead ... Also users should be able to see the files in the Archived tab (make a separate pagefor archived)
Also an Unarchive button
On Archive -> File gets removed from main dashboard and saves up in the Archived
On Unarchive -> File comes back to main dashboard

If u face any problem do join the Whatsapp group for asking doubts

**Comment by Sid-80** [comment]
@subhadeeproy3902 I am willing to work on this issue!

**Comment by Sid-80** [comment]
@subhadeeproy3902 I am getting such kind of error. How can I fix it!
![image](https://github.com/subhadeeproy3902/BloxAI/assets/101277141/43725f40-beda-4838-800e-ca044d0a6e5f)
