### ISSUE TITLE
Feat: Sorting options

### ISSUE THREAD

**Issue by ronisarkarexe** [subhadeeproy3902/BloxAI#76]
### Describe the feature

Now it is sorted by created at. We can add a sort option in the header list, such as sorting the list by name or editing. This feature enhances user experience.

### Add ScreenShots

![sort](https://github.com/subhadeeproy3902/BloxAI/assets/76697055/0b388de3-2a4e-4f61-bf09-4ec880789d4c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@ronisarkarexe Go ahead. Good observations

**Comment by AMANKANOJIYA** [comment]
Rather than manually adding the sorting and other table features, don't we utilize the docs provided by ShadCN regarding [tables](https://ui.shadcn.com/docs/components/table)? Go through this link for a better understanding

**Comment by subhadeeproy3902** [comment]
@ronisarkarexe 

its not working in the deployed link


https://github.com/subhadeeproy3902/BloxAI/assets/111780029/2b4a68e1-11c1-4086-b529-e45e3ed5a875
