### ISSUE TITLE
Feat: Edit file

### ISSUE THREAD

**Issue by ronisarkarexe** [subhadeeproy3902/BloxAI#77]
### Describe the feature

Edit the file. We can do this using the model.

### Add ScreenShots

![edit](https://github.com/subhadeeproy3902/BloxAI/assets/76697055/0fcc7368-5928-408b-bd28-cf105e6a880b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@ronisarkarexe All the best... Read the contributors.md file

**Comment by subhadeeproy3902** [comment]
@ronisarkarexe when we click the file then the file restored its content 
and also there is a save button
So no need of edit button
