### ISSUE TITLE
Updates on Added Review Us Page

### ISSUE THREAD

**Issue by AMANKANOJIYA** [subhadeeproy3902/BloxAI#87]
### Updates

- [ ] Update the Carousal Speed (not readable at this speed)
- [ ] Styling issues with the Review Form 

![image](https://github.com/subhadeeproy3902/BloxAI/assets/50018596/4d833ec4-7fef-4fb0-84e5-7ed5a3fe16ba)
_Still have the scroll height
The form does not fit the screen_

**Suggestions:**

- It would be better if we could improve the design of the review page. In addition, we can also make customer testimonials in other designs
- where the review form is not highlighted according to the UX. If we can make the form more appealing

_Originally posted by @AMANKANOJIYA in https://github.com/subhadeeproy3902/BloxAI/issues/83#issuecomment-2112973846_

**Comment by komal-agarwal5** [comment]
@subhadeeproy3902 Please assign me this issue under GSSoC24

**Comment by subhadeeproy3902** [comment]
Sure @komal-agarwal5 go ahead

**Comment by AMANKANOJIYA** [comment]
@komal-agarwal5 Any updates, or you might be facing some issues ??

**Comment by komal-agarwal5** [comment]
@AMANKANOJIYA Sorry got stuck up with some problems.Working on it,will complete in a day.

**Comment by AMANKANOJIYA** [comment]
That is no problem; then you can continue with it. If you need any help, you can ask @SwanandD121

> @AMANKANOJIYA Sorry got stuck up with some problems.Working on it,will complete in a day.
