### ISSUE TITLE
Feat: Sticky navbar

### ISSUE THREAD

**Issue by Che140401** [subhadeeproy3902/BloxAI#90]
### Describe the feature

1.Sticky navbar is just simple navbar which shows user to access navbar in every section

https://github.com/subhadeeproy3902/BloxAI/assets/109230049/57d2a187-ea4f-481d-963d-369f97b63eaa

### Add ScreenShots

Issue not sticky navbar

![Screenshot 2024-05-16 124227](https://github.com/subhadeeproy3902/BloxAI/assets/109230049/60acfc7c-eef5-4f3f-8747-023083ee48f3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
@Che140401 Go ahead and please dont change the header !
let the header be .... but only make it sticky

**Comment by subhadeeproy3902** [comment]
make a ".env.local" file and then copy paste the ".env.example" in there @Che140401

**Comment by Che140401** [comment]
Done error solved thankyou

**Comment by Che140401** [comment]
im getting error

git push --set-upstream origin chetan-branch
remote: Permission to subhadeeproy3902/BloxAI.git denied to Che140401.
fatal: unable to access 'https://github.com/subhadeeproy3902/BloxAI.git/': The requested URL returned error: 403

**Comment by subhadeeproy3902** [comment]
ig its something of your github error
cuz others pushed their code and sent me PR nicely

**Comment by AMANKANOJIYA** [comment]
> im getting error
> 
> While pushing the code to my branch im getting this error
> 
> git push --set-upstream origin chetan-branch remote: Permission to subhadeeproy3902/BloxAI.git denied to Che140401. fatal: unable to access 'https://github.com/subhadeeproy3902/BloxAI.git/': The requested URL returned error: 403

You forked the repo and used it as a remote to push the code ??

**Comment by Che140401** [comment]
I have made pr please check
