### ISSUE TITLE
BUG: Review section's form enhancement.

### ISSUE THREAD

**Issue by SwanandD121** [subhadeeproy3902/BloxAI#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The form in the review section appears significantly shorter in length compared to the form in the contact section. This inconsistency affects the visual harmony of the website and could potentially detract from the overall user experience.

**Proposed solution**
To maintain consistency and ensure a cohesive user experience throughout the website, it's recommended to adjust the length of the form in the review section to match that of the form in the contact section. By aligning the lengths of both forms, users will encounter a more uniform layout and interface, enhancing usability and aesthetic appeal.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
There is alreadyy and open issue for this @SwanandD121
