### ISSUE TITLE
Feat: Add terms and conditions page. I want to contribute under GSSOC 2024. 

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [subhadeeproy3902/BloxAI#93]
### Describe the feature

A separate page for terms and conditions which is to be directed from the footer "Terms and Conditions" link.

### Add ScreenShots

Terms and conditions

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Go ahead @ParnaRoyChowdhury777

**Comment by AMANKANOJIYA** [comment]
@ParnaRoyChowdhury777 Any Updates or Facing some issues ??

**Comment by ParnaRoyChowdhury777** [comment]
> @ParnaRoyChowdhury777 Any Updates or Facing some issues ??

I am working on it..will be pushing soon
