### ISSUE TITLE
BUG: Issue with Mobile Responsiveness on Review Us Page

### ISSUE THREAD

**Issue by Aniket-2504** [subhadeeproy3902/BloxAI#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello @subhadeeproy3902 ,

## The Issue is:

I have identified an issue with the "Review Us" page on mobile devices. The content appears to overflow outside the frame, causing misalignment and readability issues. I have attached a screenshot for better understanding.

I would like to fix this issue to ensure proper alignment and improve the mobile user experience. Please assign this issue to me, and I will work on resolving it promptly.

## Attachment: Screenshot of the "Review Us" page on mobile devices

![Screenshot 2024-05-17 214017](https://github.com/subhadeeproy3902/BloxAI/assets/145179532/4e2d4026-63c8-4043-a4cd-7c50232791ea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
There is an existing issue @Aniket-2504

**Comment by Aniket-2504** [comment]
no worries , sorry for that
