### ISSUE TITLE
BUG: Invite button is not working..I can fix it

### ISSUE THREAD

**Issue by mohit1721** [subhadeeproy3902/BloxAI#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Invite button is not working..Assign me to fix it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
There is an existing pinned issue @mohit1721

**Comment by mohit1721** [comment]
can I fix that issue ??
