### ISSUE TITLE
BUG: Code clean up and typo fix

### ISSUE THREAD

**Issue by PranotiPD** [subhadeeproy3902/BloxAI#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In many files there are imports that are not being used in the file, I would like to remove those imports so it will help in maintaining clean code, also in the header instead of "contributor" it should be modified to "contributors".

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subhadeeproy3902** [comment]
Alryt its a minor thing though go ahead @PranotiPD

**Comment by subhadeeproy3902** [comment]
If u can, try out the pinned issues !

**Comment by PranotiPD** [comment]
Ok sure, but they are already assigned  @subhadeeproy3902
